// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package evilnet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EvilNetMsg_TYPE int32

const (
	EvilNetMsg_REQREG  EvilNetMsg_TYPE = 0
	EvilNetMsg_RSPREG  EvilNetMsg_TYPE = 1
	EvilNetMsg_ROUTER  EvilNetMsg_TYPE = 2
	EvilNetMsg_REQCONN EvilNetMsg_TYPE = 3
	EvilNetMsg_RSPCONN EvilNetMsg_TYPE = 4
)

var EvilNetMsg_TYPE_name = map[int32]string{
	0: "REQREG",
	1: "RSPREG",
	2: "ROUTER",
	3: "REQCONN",
	4: "RSPCONN",
}

var EvilNetMsg_TYPE_value = map[string]int32{
	"REQREG":  0,
	"RSPREG":  1,
	"ROUTER":  2,
	"REQCONN": 3,
	"RSPCONN": 4,
}

func (x EvilNetMsg_TYPE) String() string {
	return proto.EnumName(EvilNetMsg_TYPE_name, int32(x))
}

func (EvilNetMsg_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5, 0}
}

type EvilNetReqRegMsg struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Sonkey               string   `protobuf:"bytes,2,opt,name=sonkey,proto3" json:"sonkey,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Localaddr            string   `protobuf:"bytes,4,opt,name=localaddr,proto3" json:"localaddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvilNetReqRegMsg) Reset()         { *m = EvilNetReqRegMsg{} }
func (m *EvilNetReqRegMsg) String() string { return proto.CompactTextString(m) }
func (*EvilNetReqRegMsg) ProtoMessage()    {}
func (*EvilNetReqRegMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *EvilNetReqRegMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvilNetReqRegMsg.Unmarshal(m, b)
}
func (m *EvilNetReqRegMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvilNetReqRegMsg.Marshal(b, m, deterministic)
}
func (m *EvilNetReqRegMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvilNetReqRegMsg.Merge(m, src)
}
func (m *EvilNetReqRegMsg) XXX_Size() int {
	return xxx_messageInfo_EvilNetReqRegMsg.Size(m)
}
func (m *EvilNetReqRegMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EvilNetReqRegMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EvilNetReqRegMsg proto.InternalMessageInfo

func (m *EvilNetReqRegMsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EvilNetReqRegMsg) GetSonkey() string {
	if m != nil {
		return m.Sonkey
	}
	return ""
}

func (m *EvilNetReqRegMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EvilNetReqRegMsg) GetLocaladdr() string {
	if m != nil {
		return m.Localaddr
	}
	return ""
}

type EvilNetRspRegMsg struct {
	Sonkey               string   `protobuf:"bytes,1,opt,name=sonkey,proto3" json:"sonkey,omitempty"`
	Fathername           string   `protobuf:"bytes,2,opt,name=fathername,proto3" json:"fathername,omitempty"`
	Newname              string   `protobuf:"bytes,3,opt,name=newname,proto3" json:"newname,omitempty"`
	Localaddr            string   `protobuf:"bytes,4,opt,name=localaddr,proto3" json:"localaddr,omitempty"`
	Globaladdr           string   `protobuf:"bytes,5,opt,name=globaladdr,proto3" json:"globaladdr,omitempty"`
	Result               string   `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvilNetRspRegMsg) Reset()         { *m = EvilNetRspRegMsg{} }
func (m *EvilNetRspRegMsg) String() string { return proto.CompactTextString(m) }
func (*EvilNetRspRegMsg) ProtoMessage()    {}
func (*EvilNetRspRegMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *EvilNetRspRegMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvilNetRspRegMsg.Unmarshal(m, b)
}
func (m *EvilNetRspRegMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvilNetRspRegMsg.Marshal(b, m, deterministic)
}
func (m *EvilNetRspRegMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvilNetRspRegMsg.Merge(m, src)
}
func (m *EvilNetRspRegMsg) XXX_Size() int {
	return xxx_messageInfo_EvilNetRspRegMsg.Size(m)
}
func (m *EvilNetRspRegMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EvilNetRspRegMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EvilNetRspRegMsg proto.InternalMessageInfo

func (m *EvilNetRspRegMsg) GetSonkey() string {
	if m != nil {
		return m.Sonkey
	}
	return ""
}

func (m *EvilNetRspRegMsg) GetFathername() string {
	if m != nil {
		return m.Fathername
	}
	return ""
}

func (m *EvilNetRspRegMsg) GetNewname() string {
	if m != nil {
		return m.Newname
	}
	return ""
}

func (m *EvilNetRspRegMsg) GetLocaladdr() string {
	if m != nil {
		return m.Localaddr
	}
	return ""
}

func (m *EvilNetRspRegMsg) GetGlobaladdr() string {
	if m != nil {
		return m.Globaladdr
	}
	return ""
}

func (m *EvilNetRspRegMsg) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type EvilNetRouterMsg struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  string   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvilNetRouterMsg) Reset()         { *m = EvilNetRouterMsg{} }
func (m *EvilNetRouterMsg) String() string { return proto.CompactTextString(m) }
func (*EvilNetRouterMsg) ProtoMessage()    {}
func (*EvilNetRouterMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *EvilNetRouterMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvilNetRouterMsg.Unmarshal(m, b)
}
func (m *EvilNetRouterMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvilNetRouterMsg.Marshal(b, m, deterministic)
}
func (m *EvilNetRouterMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvilNetRouterMsg.Merge(m, src)
}
func (m *EvilNetRouterMsg) XXX_Size() int {
	return xxx_messageInfo_EvilNetRouterMsg.Size(m)
}
func (m *EvilNetRouterMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EvilNetRouterMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EvilNetRouterMsg proto.InternalMessageInfo

func (m *EvilNetRouterMsg) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *EvilNetRouterMsg) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *EvilNetRouterMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EvilNetReqConnMsg struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Proto                string   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Localaddr            string   `protobuf:"bytes,3,opt,name=localaddr,proto3" json:"localaddr,omitempty"`
	Globaladdr           string   `protobuf:"bytes,4,opt,name=globaladdr,proto3" json:"globaladdr,omitempty"`
	Param                []string `protobuf:"bytes,5,rep,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvilNetReqConnMsg) Reset()         { *m = EvilNetReqConnMsg{} }
func (m *EvilNetReqConnMsg) String() string { return proto.CompactTextString(m) }
func (*EvilNetReqConnMsg) ProtoMessage()    {}
func (*EvilNetReqConnMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *EvilNetReqConnMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvilNetReqConnMsg.Unmarshal(m, b)
}
func (m *EvilNetReqConnMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvilNetReqConnMsg.Marshal(b, m, deterministic)
}
func (m *EvilNetReqConnMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvilNetReqConnMsg.Merge(m, src)
}
func (m *EvilNetReqConnMsg) XXX_Size() int {
	return xxx_messageInfo_EvilNetReqConnMsg.Size(m)
}
func (m *EvilNetReqConnMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EvilNetReqConnMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EvilNetReqConnMsg proto.InternalMessageInfo

func (m *EvilNetReqConnMsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EvilNetReqConnMsg) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *EvilNetReqConnMsg) GetLocaladdr() string {
	if m != nil {
		return m.Localaddr
	}
	return ""
}

func (m *EvilNetReqConnMsg) GetGlobaladdr() string {
	if m != nil {
		return m.Globaladdr
	}
	return ""
}

func (m *EvilNetReqConnMsg) GetParam() []string {
	if m != nil {
		return m.Param
	}
	return nil
}

type EvilNetRspConnMsg struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Proto                string   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Localaddr            string   `protobuf:"bytes,4,opt,name=localaddr,proto3" json:"localaddr,omitempty"`
	Globaladdr           string   `protobuf:"bytes,5,opt,name=globaladdr,proto3" json:"globaladdr,omitempty"`
	Param                []string `protobuf:"bytes,6,rep,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvilNetRspConnMsg) Reset()         { *m = EvilNetRspConnMsg{} }
func (m *EvilNetRspConnMsg) String() string { return proto.CompactTextString(m) }
func (*EvilNetRspConnMsg) ProtoMessage()    {}
func (*EvilNetRspConnMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *EvilNetRspConnMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvilNetRspConnMsg.Unmarshal(m, b)
}
func (m *EvilNetRspConnMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvilNetRspConnMsg.Marshal(b, m, deterministic)
}
func (m *EvilNetRspConnMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvilNetRspConnMsg.Merge(m, src)
}
func (m *EvilNetRspConnMsg) XXX_Size() int {
	return xxx_messageInfo_EvilNetRspConnMsg.Size(m)
}
func (m *EvilNetRspConnMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EvilNetRspConnMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EvilNetRspConnMsg proto.InternalMessageInfo

func (m *EvilNetRspConnMsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EvilNetRspConnMsg) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *EvilNetRspConnMsg) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *EvilNetRspConnMsg) GetLocaladdr() string {
	if m != nil {
		return m.Localaddr
	}
	return ""
}

func (m *EvilNetRspConnMsg) GetGlobaladdr() string {
	if m != nil {
		return m.Globaladdr
	}
	return ""
}

func (m *EvilNetRspConnMsg) GetParam() []string {
	if m != nil {
		return m.Param
	}
	return nil
}

type EvilNetMsg struct {
	Type                 int32              `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ReqRegMsg            *EvilNetReqRegMsg  `protobuf:"bytes,2,opt,name=reqRegMsg,proto3" json:"reqRegMsg,omitempty"`
	RspRegMsg            *EvilNetRspRegMsg  `protobuf:"bytes,3,opt,name=rspRegMsg,proto3" json:"rspRegMsg,omitempty"`
	RouterMsg            *EvilNetRouterMsg  `protobuf:"bytes,4,opt,name=routerMsg,proto3" json:"routerMsg,omitempty"`
	ReqConnMsg           *EvilNetReqConnMsg `protobuf:"bytes,5,opt,name=reqConnMsg,proto3" json:"reqConnMsg,omitempty"`
	RspConnMsg           *EvilNetRspConnMsg `protobuf:"bytes,6,opt,name=rspConnMsg,proto3" json:"rspConnMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EvilNetMsg) Reset()         { *m = EvilNetMsg{} }
func (m *EvilNetMsg) String() string { return proto.CompactTextString(m) }
func (*EvilNetMsg) ProtoMessage()    {}
func (*EvilNetMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *EvilNetMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvilNetMsg.Unmarshal(m, b)
}
func (m *EvilNetMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvilNetMsg.Marshal(b, m, deterministic)
}
func (m *EvilNetMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvilNetMsg.Merge(m, src)
}
func (m *EvilNetMsg) XXX_Size() int {
	return xxx_messageInfo_EvilNetMsg.Size(m)
}
func (m *EvilNetMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EvilNetMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EvilNetMsg proto.InternalMessageInfo

func (m *EvilNetMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *EvilNetMsg) GetReqRegMsg() *EvilNetReqRegMsg {
	if m != nil {
		return m.ReqRegMsg
	}
	return nil
}

func (m *EvilNetMsg) GetRspRegMsg() *EvilNetRspRegMsg {
	if m != nil {
		return m.RspRegMsg
	}
	return nil
}

func (m *EvilNetMsg) GetRouterMsg() *EvilNetRouterMsg {
	if m != nil {
		return m.RouterMsg
	}
	return nil
}

func (m *EvilNetMsg) GetReqConnMsg() *EvilNetReqConnMsg {
	if m != nil {
		return m.ReqConnMsg
	}
	return nil
}

func (m *EvilNetMsg) GetRspConnMsg() *EvilNetRspConnMsg {
	if m != nil {
		return m.RspConnMsg
	}
	return nil
}

func init() {
	proto.RegisterEnum("EvilNetMsg_TYPE", EvilNetMsg_TYPE_name, EvilNetMsg_TYPE_value)
	proto.RegisterType((*EvilNetReqRegMsg)(nil), "EvilNetReqRegMsg")
	proto.RegisterType((*EvilNetRspRegMsg)(nil), "EvilNetRspRegMsg")
	proto.RegisterType((*EvilNetRouterMsg)(nil), "EvilNetRouterMsg")
	proto.RegisterType((*EvilNetReqConnMsg)(nil), "EvilNetReqConnMsg")
	proto.RegisterType((*EvilNetRspConnMsg)(nil), "EvilNetRspConnMsg")
	proto.RegisterType((*EvilNetMsg)(nil), "EvilNetMsg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcb, 0xce, 0xd2, 0x40,
	0x14, 0x80, 0x2d, 0xbd, 0x90, 0x1e, 0x5c, 0x94, 0x89, 0x31, 0x5d, 0x18, 0x43, 0xba, 0x72, 0x85,
	0x09, 0xbe, 0x81, 0xd8, 0x98, 0x98, 0xc8, 0x65, 0xc0, 0x85, 0xee, 0x06, 0x3a, 0x56, 0x62, 0x69,
	0xeb, 0xcc, 0x80, 0xe1, 0x29, 0x7c, 0x0c, 0xdf, 0xc1, 0xb7, 0xf1, 0x4d, 0xcc, 0x9c, 0x5e, 0x66,
	0x10, 0x43, 0x62, 0xfe, 0xdd, 0xb9, 0x9f, 0xef, 0x5c, 0x20, 0x3c, 0xca, 0x7c, 0x5a, 0x8b, 0x4a,
	0x55, 0x49, 0x09, 0x51, 0x7a, 0x3e, 0x14, 0x0b, 0xae, 0x28, 0xff, 0x46, 0x79, 0xfe, 0x5e, 0xe6,
	0x24, 0x02, 0xf7, 0x2b, 0xbf, 0xc4, 0xce, 0xc4, 0x79, 0x11, 0x52, 0x2d, 0x92, 0xa7, 0x10, 0xc8,
	0xaa, 0xd4, 0xc6, 0x01, 0x1a, 0x5b, 0x8d, 0x10, 0xf0, 0x4a, 0x76, 0xe4, 0xb1, 0x8b, 0x56, 0x94,
	0xc9, 0x33, 0x08, 0x8b, 0x6a, 0xcf, 0x0a, 0x96, 0x65, 0x22, 0xf6, 0xd0, 0x61, 0x0c, 0xc9, 0x2f,
	0xc7, 0x34, 0x94, 0x75, 0xdb, 0xd0, 0x94, 0x77, 0xae, 0xca, 0x3f, 0x07, 0xf8, 0xcc, 0xd4, 0x17,
	0x2e, 0xb0, 0x49, 0xd3, 0xda, 0xb2, 0x90, 0x18, 0x86, 0x25, 0xff, 0x6e, 0x11, 0x74, 0xea, 0x7d,
	0x08, 0x5d, 0x37, 0x2f, 0xaa, 0x5d, 0xeb, 0xf6, 0x9b, 0xba, 0xc6, 0xa2, 0x79, 0x04, 0x97, 0xa7,
	0x42, 0xc5, 0x41, 0xc3, 0xd3, 0x68, 0xc9, 0x3b, 0xc3, 0x5e, 0x9d, 0x14, 0x17, 0xed, 0xb2, 0xa4,
	0xd8, 0x77, 0xcb, 0x92, 0x62, 0xaf, 0x2d, 0x99, 0x54, 0x2d, 0xae, 0x16, 0xf5, 0x9a, 0x32, 0xa6,
	0x18, 0x42, 0x3e, 0xa6, 0x28, 0x27, 0x3f, 0x1c, 0x18, 0x9b, 0xcd, 0xcf, 0xab, 0xb2, 0xfc, 0xf7,
	0xea, 0x9f, 0x80, 0x8f, 0x97, 0x6a, 0xeb, 0x35, 0xca, 0xf5, 0x7c, 0xee, 0xfd, 0xf9, 0xbc, 0x9b,
	0xf9, 0x74, 0x4d, 0x26, 0xd8, 0x31, 0xf6, 0x27, 0x2e, 0xd6, 0xd4, 0x4a, 0xf2, 0xd3, 0x22, 0x92,
	0xf5, 0xff, 0x12, 0x99, 0x9d, 0xb9, 0xf6, 0xce, 0x1e, 0x78, 0x89, 0x9e, 0x34, 0xb0, 0x49, 0x7f,
	0x0f, 0x00, 0x5a, 0x52, 0x8d, 0x48, 0xc0, 0x53, 0x97, 0x9a, 0x23, 0xa3, 0x4f, 0x51, 0x26, 0x2f,
	0x21, 0x14, 0xdd, 0x43, 0x23, 0xe8, 0x68, 0x36, 0x9e, 0xfe, 0xfd, 0xe9, 0xd4, 0xc4, 0x60, 0x42,
	0xf7, 0x90, 0x38, 0x82, 0x9d, 0xd0, 0x39, 0xa8, 0x89, 0xc1, 0x84, 0xee, 0x0b, 0x70, 0x30, 0x3b,
	0xa1, 0x73, 0x50, 0x13, 0x43, 0x66, 0x00, 0xa2, 0xbf, 0x34, 0xce, 0x3a, 0x9a, 0x91, 0xe9, 0xcd,
	0x0f, 0x50, 0x2b, 0x0a, 0x73, 0xfa, 0x5b, 0xe0, 0x37, 0xda, 0x39, 0xbd, 0x87, 0x5a, 0x51, 0xc9,
	0x1b, 0xf0, 0xb6, 0x1f, 0x57, 0x29, 0x01, 0x08, 0x68, 0xba, 0xa6, 0xe9, 0xdb, 0xe8, 0x11, 0xca,
	0x9b, 0x95, 0x96, 0x1d, 0x94, 0x97, 0x1f, 0xb6, 0x29, 0x8d, 0x06, 0x64, 0x04, 0x43, 0x9a, 0xae,
	0xe7, 0xcb, 0xc5, 0x22, 0x72, 0x51, 0xd9, 0xac, 0x50, 0xf1, 0x5e, 0x87, 0x9f, 0x86, 0xfc, 0x7c,
	0x28, 0x4a, 0xae, 0x76, 0x01, 0x5e, 0xf8, 0xd5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x59,
	0xb5, 0x81, 0x37, 0x04, 0x00, 0x00,
}
