// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PROXY_PROTO int32

const (
	PROXY_PROTO_TCP   PROXY_PROTO = 0
	PROXY_PROTO_UDP   PROXY_PROTO = 1
	PROXY_PROTO_RUDP  PROXY_PROTO = 2
	PROXY_PROTO_RICMP PROXY_PROTO = 3
)

var PROXY_PROTO_name = map[int32]string{
	0: "TCP",
	1: "UDP",
	2: "RUDP",
	3: "RICMP",
}

var PROXY_PROTO_value = map[string]int32{
	"TCP":   0,
	"UDP":   1,
	"RUDP":  2,
	"RICMP": 3,
}

func (x PROXY_PROTO) String() string {
	return proto.EnumName(PROXY_PROTO_name, int32(x))
}

func (PROXY_PROTO) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

type CLIENT_TYPE int32

const (
	CLIENT_TYPE_PROXY          CLIENT_TYPE = 0
	CLIENT_TYPE_REVERSE_PROXY  CLIENT_TYPE = 1
	CLIENT_TYPE_SOCKS5         CLIENT_TYPE = 2
	CLIENT_TYPE_REVERSE_SOCKS5 CLIENT_TYPE = 3
)

var CLIENT_TYPE_name = map[int32]string{
	0: "PROXY",
	1: "REVERSE_PROXY",
	2: "SOCKS5",
	3: "REVERSE_SOCKS5",
}

var CLIENT_TYPE_value = map[string]int32{
	"PROXY":          0,
	"REVERSE_PROXY":  1,
	"SOCKS5":         2,
	"REVERSE_SOCKS5": 3,
}

func (x CLIENT_TYPE) String() string {
	return proto.EnumName(CLIENT_TYPE_name, int32(x))
}

func (CLIENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

type FRAME_TYPE int32

const (
	FRAME_TYPE_LOGIN    FRAME_TYPE = 0
	FRAME_TYPE_LOGINRSP FRAME_TYPE = 1
	FRAME_TYPE_DATA     FRAME_TYPE = 2
	FRAME_TYPE_PING     FRAME_TYPE = 3
	FRAME_TYPE_PONG     FRAME_TYPE = 4
	FRAME_TYPE_OPEN     FRAME_TYPE = 5
	FRAME_TYPE_OPENRSP  FRAME_TYPE = 6
	FRAME_TYPE_CLOSE    FRAME_TYPE = 7
)

var FRAME_TYPE_name = map[int32]string{
	0: "LOGIN",
	1: "LOGINRSP",
	2: "DATA",
	3: "PING",
	4: "PONG",
	5: "OPEN",
	6: "OPENRSP",
	7: "CLOSE",
}

var FRAME_TYPE_value = map[string]int32{
	"LOGIN":    0,
	"LOGINRSP": 1,
	"DATA":     2,
	"PING":     3,
	"PONG":     4,
	"OPEN":     5,
	"OPENRSP":  6,
	"CLOSE":    7,
}

func (x FRAME_TYPE) String() string {
	return proto.EnumName(FRAME_TYPE_name, int32(x))
}

func (FRAME_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

type LoginFrame struct {
	Proxyproto           PROXY_PROTO `protobuf:"varint,1,opt,name=proxyproto,proto3,enum=PROXY_PROTO" json:"proxyproto,omitempty"`
	Clienttype           CLIENT_TYPE `protobuf:"varint,2,opt,name=clienttype,proto3,enum=CLIENT_TYPE" json:"clienttype,omitempty"`
	Fromaddr             string      `protobuf:"bytes,3,opt,name=fromaddr,proto3" json:"fromaddr,omitempty"`
	Toaddr               string      `protobuf:"bytes,4,opt,name=toaddr,proto3" json:"toaddr,omitempty"`
	Compress             bool        `protobuf:"varint,5,opt,name=compress,proto3" json:"compress,omitempty"`
	Encrypt              bool        `protobuf:"varint,6,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginFrame) Reset()         { *m = LoginFrame{} }
func (m *LoginFrame) String() string { return proto.CompactTextString(m) }
func (*LoginFrame) ProtoMessage()    {}
func (*LoginFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *LoginFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginFrame.Unmarshal(m, b)
}
func (m *LoginFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginFrame.Marshal(b, m, deterministic)
}
func (m *LoginFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginFrame.Merge(m, src)
}
func (m *LoginFrame) XXX_Size() int {
	return xxx_messageInfo_LoginFrame.Size(m)
}
func (m *LoginFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginFrame.DiscardUnknown(m)
}

var xxx_messageInfo_LoginFrame proto.InternalMessageInfo

func (m *LoginFrame) GetProxyproto() PROXY_PROTO {
	if m != nil {
		return m.Proxyproto
	}
	return PROXY_PROTO_TCP
}

func (m *LoginFrame) GetClienttype() CLIENT_TYPE {
	if m != nil {
		return m.Clienttype
	}
	return CLIENT_TYPE_PROXY
}

func (m *LoginFrame) GetFromaddr() string {
	if m != nil {
		return m.Fromaddr
	}
	return ""
}

func (m *LoginFrame) GetToaddr() string {
	if m != nil {
		return m.Toaddr
	}
	return ""
}

func (m *LoginFrame) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *LoginFrame) GetEncrypt() bool {
	if m != nil {
		return m.Encrypt
	}
	return false
}

type LoginRspFrame struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRspFrame) Reset()         { *m = LoginRspFrame{} }
func (m *LoginRspFrame) String() string { return proto.CompactTextString(m) }
func (*LoginRspFrame) ProtoMessage()    {}
func (*LoginRspFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *LoginRspFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRspFrame.Unmarshal(m, b)
}
func (m *LoginRspFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRspFrame.Marshal(b, m, deterministic)
}
func (m *LoginRspFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRspFrame.Merge(m, src)
}
func (m *LoginRspFrame) XXX_Size() int {
	return xxx_messageInfo_LoginRspFrame.Size(m)
}
func (m *LoginRspFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRspFrame.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRspFrame proto.InternalMessageInfo

func (m *LoginRspFrame) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *LoginRspFrame) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PingFrame struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingFrame) Reset()         { *m = PingFrame{} }
func (m *PingFrame) String() string { return proto.CompactTextString(m) }
func (*PingFrame) ProtoMessage()    {}
func (*PingFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *PingFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingFrame.Unmarshal(m, b)
}
func (m *PingFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingFrame.Marshal(b, m, deterministic)
}
func (m *PingFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingFrame.Merge(m, src)
}
func (m *PingFrame) XXX_Size() int {
	return xxx_messageInfo_PingFrame.Size(m)
}
func (m *PingFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PingFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PingFrame proto.InternalMessageInfo

func (m *PingFrame) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PongFrame struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongFrame) Reset()         { *m = PongFrame{} }
func (m *PongFrame) String() string { return proto.CompactTextString(m) }
func (*PongFrame) ProtoMessage()    {}
func (*PongFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *PongFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongFrame.Unmarshal(m, b)
}
func (m *PongFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongFrame.Marshal(b, m, deterministic)
}
func (m *PongFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongFrame.Merge(m, src)
}
func (m *PongFrame) XXX_Size() int {
	return xxx_messageInfo_PongFrame.Size(m)
}
func (m *PongFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PongFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PongFrame proto.InternalMessageInfo

func (m *PongFrame) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type OpenConnFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenConnFrame) Reset()         { *m = OpenConnFrame{} }
func (m *OpenConnFrame) String() string { return proto.CompactTextString(m) }
func (*OpenConnFrame) ProtoMessage()    {}
func (*OpenConnFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *OpenConnFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenConnFrame.Unmarshal(m, b)
}
func (m *OpenConnFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenConnFrame.Marshal(b, m, deterministic)
}
func (m *OpenConnFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenConnFrame.Merge(m, src)
}
func (m *OpenConnFrame) XXX_Size() int {
	return xxx_messageInfo_OpenConnFrame.Size(m)
}
func (m *OpenConnFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenConnFrame.DiscardUnknown(m)
}

var xxx_messageInfo_OpenConnFrame proto.InternalMessageInfo

func (m *OpenConnFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type OpenConnRspFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ret                  bool     `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenConnRspFrame) Reset()         { *m = OpenConnRspFrame{} }
func (m *OpenConnRspFrame) String() string { return proto.CompactTextString(m) }
func (*OpenConnRspFrame) ProtoMessage()    {}
func (*OpenConnRspFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *OpenConnRspFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenConnRspFrame.Unmarshal(m, b)
}
func (m *OpenConnRspFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenConnRspFrame.Marshal(b, m, deterministic)
}
func (m *OpenConnRspFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenConnRspFrame.Merge(m, src)
}
func (m *OpenConnRspFrame) XXX_Size() int {
	return xxx_messageInfo_OpenConnRspFrame.Size(m)
}
func (m *OpenConnRspFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenConnRspFrame.DiscardUnknown(m)
}

var xxx_messageInfo_OpenConnRspFrame proto.InternalMessageInfo

func (m *OpenConnRspFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenConnRspFrame) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *OpenConnRspFrame) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CloseFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseFrame) Reset()         { *m = CloseFrame{} }
func (m *CloseFrame) String() string { return proto.CompactTextString(m) }
func (*CloseFrame) ProtoMessage()    {}
func (*CloseFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *CloseFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseFrame.Unmarshal(m, b)
}
func (m *CloseFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseFrame.Marshal(b, m, deterministic)
}
func (m *CloseFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseFrame.Merge(m, src)
}
func (m *CloseFrame) XXX_Size() int {
	return xxx_messageInfo_CloseFrame.Size(m)
}
func (m *CloseFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseFrame.DiscardUnknown(m)
}

var xxx_messageInfo_CloseFrame proto.InternalMessageInfo

func (m *CloseFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DataFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Compress             bool     `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	Encrypt              bool     `protobuf:"varint,3,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataFrame) Reset()         { *m = DataFrame{} }
func (m *DataFrame) String() string { return proto.CompactTextString(m) }
func (*DataFrame) ProtoMessage()    {}
func (*DataFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *DataFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFrame.Unmarshal(m, b)
}
func (m *DataFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFrame.Marshal(b, m, deterministic)
}
func (m *DataFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFrame.Merge(m, src)
}
func (m *DataFrame) XXX_Size() int {
	return xxx_messageInfo_DataFrame.Size(m)
}
func (m *DataFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFrame.DiscardUnknown(m)
}

var xxx_messageInfo_DataFrame proto.InternalMessageInfo

func (m *DataFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataFrame) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *DataFrame) GetEncrypt() bool {
	if m != nil {
		return m.Encrypt
	}
	return false
}

func (m *DataFrame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProxyFrame struct {
	Type                 FRAME_TYPE        `protobuf:"varint,1,opt,name=type,proto3,enum=FRAME_TYPE" json:"type,omitempty"`
	LoginFrame           *LoginFrame       `protobuf:"bytes,2,opt,name=loginFrame,proto3" json:"loginFrame,omitempty"`
	LoginRspFrame        *LoginRspFrame    `protobuf:"bytes,3,opt,name=loginRspFrame,proto3" json:"loginRspFrame,omitempty"`
	DataFrame            *DataFrame        `protobuf:"bytes,4,opt,name=dataFrame,proto3" json:"dataFrame,omitempty"`
	PingFrame            *PingFrame        `protobuf:"bytes,5,opt,name=pingFrame,proto3" json:"pingFrame,omitempty"`
	PongFrame            *PongFrame        `protobuf:"bytes,6,opt,name=pongFrame,proto3" json:"pongFrame,omitempty"`
	OpenFrame            *OpenConnFrame    `protobuf:"bytes,7,opt,name=openFrame,proto3" json:"openFrame,omitempty"`
	OpenRspFrame         *OpenConnRspFrame `protobuf:"bytes,8,opt,name=openRspFrame,proto3" json:"openRspFrame,omitempty"`
	CloseFrame           *CloseFrame       `protobuf:"bytes,9,opt,name=closeFrame,proto3" json:"closeFrame,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProxyFrame) Reset()         { *m = ProxyFrame{} }
func (m *ProxyFrame) String() string { return proto.CompactTextString(m) }
func (*ProxyFrame) ProtoMessage()    {}
func (*ProxyFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{8}
}

func (m *ProxyFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyFrame.Unmarshal(m, b)
}
func (m *ProxyFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyFrame.Marshal(b, m, deterministic)
}
func (m *ProxyFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyFrame.Merge(m, src)
}
func (m *ProxyFrame) XXX_Size() int {
	return xxx_messageInfo_ProxyFrame.Size(m)
}
func (m *ProxyFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyFrame.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyFrame proto.InternalMessageInfo

func (m *ProxyFrame) GetType() FRAME_TYPE {
	if m != nil {
		return m.Type
	}
	return FRAME_TYPE_LOGIN
}

func (m *ProxyFrame) GetLoginFrame() *LoginFrame {
	if m != nil {
		return m.LoginFrame
	}
	return nil
}

func (m *ProxyFrame) GetLoginRspFrame() *LoginRspFrame {
	if m != nil {
		return m.LoginRspFrame
	}
	return nil
}

func (m *ProxyFrame) GetDataFrame() *DataFrame {
	if m != nil {
		return m.DataFrame
	}
	return nil
}

func (m *ProxyFrame) GetPingFrame() *PingFrame {
	if m != nil {
		return m.PingFrame
	}
	return nil
}

func (m *ProxyFrame) GetPongFrame() *PongFrame {
	if m != nil {
		return m.PongFrame
	}
	return nil
}

func (m *ProxyFrame) GetOpenFrame() *OpenConnFrame {
	if m != nil {
		return m.OpenFrame
	}
	return nil
}

func (m *ProxyFrame) GetOpenRspFrame() *OpenConnRspFrame {
	if m != nil {
		return m.OpenRspFrame
	}
	return nil
}

func (m *ProxyFrame) GetCloseFrame() *CloseFrame {
	if m != nil {
		return m.CloseFrame
	}
	return nil
}

func init() {
	proto.RegisterEnum("PROXY_PROTO", PROXY_PROTO_name, PROXY_PROTO_value)
	proto.RegisterEnum("CLIENT_TYPE", CLIENT_TYPE_name, CLIENT_TYPE_value)
	proto.RegisterEnum("FRAME_TYPE", FRAME_TYPE_name, FRAME_TYPE_value)
	proto.RegisterType((*LoginFrame)(nil), "LoginFrame")
	proto.RegisterType((*LoginRspFrame)(nil), "LoginRspFrame")
	proto.RegisterType((*PingFrame)(nil), "PingFrame")
	proto.RegisterType((*PongFrame)(nil), "PongFrame")
	proto.RegisterType((*OpenConnFrame)(nil), "OpenConnFrame")
	proto.RegisterType((*OpenConnRspFrame)(nil), "OpenConnRspFrame")
	proto.RegisterType((*CloseFrame)(nil), "CloseFrame")
	proto.RegisterType((*DataFrame)(nil), "DataFrame")
	proto.RegisterType((*ProxyFrame)(nil), "ProxyFrame")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcb, 0x4e, 0xdb, 0x40,
	0x14, 0xc5, 0x76, 0x5e, 0xbe, 0x4e, 0xa2, 0x61, 0x16, 0x95, 0x55, 0x55, 0x02, 0x65, 0x15, 0x51,
	0xe4, 0x45, 0x80, 0x0f, 0xa0, 0xc6, 0xa0, 0x88, 0x10, 0x5b, 0x37, 0x69, 0x55, 0xba, 0x41, 0x6e,
	0x3c, 0x45, 0x96, 0x12, 0x8f, 0xe5, 0x78, 0x51, 0xfe, 0xa6, 0xdf, 0xd4, 0x2f, 0xaa, 0xe6, 0xfa,
	0x19, 0x4a, 0xbb, 0x3b, 0x77, 0xce, 0xb9, 0x33, 0xf7, 0x71, 0x6c, 0xb0, 0xd2, 0x4c, 0xfe, 0x7c,
	0x71, 0xd2, 0x4c, 0xe6, 0x72, 0xf2, 0x5b, 0x03, 0x58, 0xc8, 0xe7, 0x38, 0xb9, 0xcd, 0xc2, 0x9d,
	0xe0, 0xe7, 0x00, 0xc4, 0x12, 0x69, 0x6b, 0xa7, 0xda, 0x74, 0x3c, 0x1b, 0x3a, 0x01, 0xfa, 0x5f,
	0x1f, 0x9f, 0x02, 0xf4, 0xd7, 0x3e, 0xb6, 0x78, 0xa5, 0xde, 0x6c, 0x63, 0x91, 0xe4, 0xf9, 0x4b,
	0x2a, 0x6c, 0xbd, 0x54, 0xbb, 0x8b, 0xb9, 0xb7, 0x5c, 0x3f, 0xad, 0x1f, 0x03, 0x0f, 0x5b, 0x3c,
	0x7f, 0x0f, 0x83, 0x1f, 0x99, 0xdc, 0x85, 0x51, 0x94, 0xd9, 0xc6, 0xa9, 0x36, 0x35, 0xb1, 0x8e,
	0xf9, 0x3b, 0xe8, 0xe5, 0x92, 0x98, 0x0e, 0x31, 0x65, 0xa4, 0x72, 0x36, 0x72, 0x97, 0x66, 0x62,
	0xbf, 0xb7, 0xbb, 0xa7, 0xda, 0x74, 0x80, 0x75, 0xcc, 0x6d, 0xe8, 0x8b, 0x64, 0x93, 0xbd, 0xa4,
	0xb9, 0xdd, 0x23, 0xaa, 0x0a, 0x27, 0x17, 0x30, 0xa2, 0x9e, 0x70, 0x9f, 0x16, 0x6d, 0x31, 0x30,
	0x32, 0x91, 0x53, 0x3f, 0x03, 0x54, 0x50, 0x9d, 0xec, 0xf6, 0xcf, 0x54, 0xb3, 0x89, 0x0a, 0x4e,
	0x4e, 0xc0, 0x0c, 0xe2, 0xe4, 0xb9, 0x48, 0xe0, 0xd0, 0xc9, 0xe3, 0x9d, 0xa0, 0x0c, 0x03, 0x09,
	0x93, 0x40, 0xfe, 0x5f, 0x30, 0xf2, 0x53, 0x91, 0xb8, 0x32, 0x29, 0xa7, 0x39, 0x06, 0x3d, 0x8e,
	0x48, 0x62, 0xa2, 0x1e, 0x47, 0x93, 0x5b, 0x60, 0x95, 0xa0, 0x2e, 0xed, 0x95, 0xa6, 0x2a, 0x55,
	0xff, 0xab, 0x54, 0xa3, 0x29, 0xf5, 0x03, 0x80, 0xbb, 0x95, 0x7b, 0xf1, 0xf6, 0x2b, 0x02, 0xcc,
	0x9b, 0x30, 0x0f, 0xdf, 0xbe, 0xbe, 0x3d, 0x50, 0xfd, 0xdf, 0x03, 0x35, 0x0e, 0x06, 0xaa, 0xba,
	0x8d, 0xc2, 0x3c, 0xa4, 0xe5, 0x0c, 0x91, 0xf0, 0xe4, 0x97, 0x01, 0x10, 0x28, 0x2f, 0x14, 0x0f,
	0x9d, 0x40, 0x87, 0x5c, 0x50, 0x78, 0xc6, 0x72, 0x6e, 0xf1, 0xfa, 0xc1, 0x2b, 0x4c, 0x40, 0x04,
	0xff, 0x08, 0xb0, 0xad, 0x8d, 0x46, 0x6f, 0x5b, 0x33, 0xcb, 0x69, 0xbc, 0x87, 0x2d, 0x9a, 0x5f,
	0xc2, 0x68, 0xdb, 0xde, 0x20, 0x15, 0x64, 0xcd, 0xc6, 0xce, 0xc1, 0x5e, 0xf1, 0x50, 0xc4, 0xa7,
	0x60, 0x46, 0x55, 0xe7, 0x54, 0xab, 0x35, 0x03, 0xa7, 0x9e, 0x05, 0x36, 0xa4, 0x52, 0xa6, 0xd5,
	0xb2, 0xc9, 0x58, 0x4a, 0x59, 0xaf, 0x1f, 0x1b, 0x92, 0x94, 0xd5, 0xd6, 0xc9, 0x67, 0xa4, 0x94,
	0x8d, 0xb2, 0xb6, 0xc4, 0x39, 0x98, 0x32, 0x15, 0x65, 0x7f, 0xfd, 0xb2, 0xde, 0x03, 0x43, 0x60,
	0x23, 0xe0, 0x57, 0x30, 0x54, 0x41, 0xdd, 0xe0, 0x80, 0x12, 0x8e, 0x9d, 0xd7, 0x06, 0xc1, 0x03,
	0x99, 0x9a, 0xe2, 0xa6, 0x5e, 0xbd, 0x6d, 0x96, 0x53, 0x6c, 0xdc, 0x80, 0x2d, 0xfa, 0xec, 0x12,
	0xac, 0xd6, 0xa7, 0xcb, 0xfb, 0x60, 0xac, 0xdd, 0x80, 0x1d, 0x29, 0xf0, 0xf9, 0x26, 0x60, 0x1a,
	0x1f, 0x40, 0x07, 0x15, 0xd2, 0xb9, 0x09, 0x5d, 0x9c, 0xbb, 0x0f, 0x01, 0x33, 0xce, 0xee, 0xc1,
	0x6a, 0x7d, 0xc2, 0x8a, 0xa1, 0x4b, 0xd8, 0x11, 0x3f, 0x86, 0x11, 0x7a, 0x5f, 0x3c, 0x5c, 0x79,
	0x4f, 0xc5, 0x91, 0xc6, 0x01, 0x7a, 0x2b, 0xdf, 0xbd, 0x5f, 0x5d, 0x31, 0x9d, 0x73, 0x18, 0x57,
	0x74, 0x79, 0x66, 0x9c, 0x09, 0x80, 0xc6, 0x09, 0xea, 0xae, 0x85, 0x7f, 0x37, 0x5f, 0xb2, 0x23,
	0x3e, 0x84, 0x01, 0x41, 0x5c, 0x95, 0x85, 0xdc, 0x5c, 0xaf, 0xaf, 0x99, 0xae, 0x50, 0x30, 0x5f,
	0xde, 0x31, 0x83, 0x90, 0xbf, 0xbc, 0x63, 0x1d, 0x85, 0xfc, 0xc0, 0x5b, 0xb2, 0x2e, 0xb7, 0xa0,
	0xaf, 0x90, 0x4a, 0xea, 0xa9, 0xdb, 0xdc, 0x85, 0xbf, 0xf2, 0x58, 0xff, 0x53, 0xff, 0x5b, 0x97,
	0xfe, 0x4b, 0xdf, 0x7b, 0xf4, 0x67, 0xba, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xf6, 0xb8,
	0xdf, 0xe5, 0x04, 0x00, 0x00,
}
