// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PROXY_PROTO int32

const (
	PROXY_PROTO_TCP   PROXY_PROTO = 0
	PROXY_PROTO_UDP   PROXY_PROTO = 1
	PROXY_PROTO_RUDP  PROXY_PROTO = 2
	PROXY_PROTO_RICMP PROXY_PROTO = 3
)

var PROXY_PROTO_name = map[int32]string{
	0: "TCP",
	1: "UDP",
	2: "RUDP",
	3: "RICMP",
}

var PROXY_PROTO_value = map[string]int32{
	"TCP":   0,
	"UDP":   1,
	"RUDP":  2,
	"RICMP": 3,
}

func (x PROXY_PROTO) String() string {
	return proto.EnumName(PROXY_PROTO_name, int32(x))
}

func (PROXY_PROTO) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

type CLIENT_TYPE int32

const (
	// client fromaddr -> server toaddr
	CLIENT_TYPE_PROXY CLIENT_TYPE = 0
	// server fromaddr -> client toaddr
	CLIENT_TYPE_REVERSE_PROXY CLIENT_TYPE = 1
	// client fromaddr -> server
	CLIENT_TYPE_SOCKS5 CLIENT_TYPE = 2
	// server fromaddr -> client
	CLIENT_TYPE_REVERSE_SOCKS5 CLIENT_TYPE = 3
)

var CLIENT_TYPE_name = map[int32]string{
	0: "PROXY",
	1: "REVERSE_PROXY",
	2: "SOCKS5",
	3: "REVERSE_SOCKS5",
}

var CLIENT_TYPE_value = map[string]int32{
	"PROXY":          0,
	"REVERSE_PROXY":  1,
	"SOCKS5":         2,
	"REVERSE_SOCKS5": 3,
}

func (x CLIENT_TYPE) String() string {
	return proto.EnumName(CLIENT_TYPE_name, int32(x))
}

func (CLIENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

type FRAME_TYPE int32

const (
	FRAME_TYPE_LOGIN    FRAME_TYPE = 0
	FRAME_TYPE_LOGINRSP FRAME_TYPE = 1
	FRAME_TYPE_DATA     FRAME_TYPE = 2
	FRAME_TYPE_PING     FRAME_TYPE = 3
	FRAME_TYPE_PONG     FRAME_TYPE = 4
	FRAME_TYPE_OPEN     FRAME_TYPE = 5
	FRAME_TYPE_OPENRSP  FRAME_TYPE = 6
	FRAME_TYPE_CLOSE    FRAME_TYPE = 7
)

var FRAME_TYPE_name = map[int32]string{
	0: "LOGIN",
	1: "LOGINRSP",
	2: "DATA",
	3: "PING",
	4: "PONG",
	5: "OPEN",
	6: "OPENRSP",
	7: "CLOSE",
}

var FRAME_TYPE_value = map[string]int32{
	"LOGIN":    0,
	"LOGINRSP": 1,
	"DATA":     2,
	"PING":     3,
	"PONG":     4,
	"OPEN":     5,
	"OPENRSP":  6,
	"CLOSE":    7,
}

func (x FRAME_TYPE) String() string {
	return proto.EnumName(FRAME_TYPE_name, int32(x))
}

func (FRAME_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

type LoginFrame struct {
	Proxyproto           PROXY_PROTO `protobuf:"varint,1,opt,name=proxyproto,proto3,enum=PROXY_PROTO" json:"proxyproto,omitempty"`
	Clienttype           CLIENT_TYPE `protobuf:"varint,2,opt,name=clienttype,proto3,enum=CLIENT_TYPE" json:"clienttype,omitempty"`
	Fromaddr             string      `protobuf:"bytes,3,opt,name=fromaddr,proto3" json:"fromaddr,omitempty"`
	Toaddr               string      `protobuf:"bytes,4,opt,name=toaddr,proto3" json:"toaddr,omitempty"`
	Name                 string      `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string      `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginFrame) Reset()         { *m = LoginFrame{} }
func (m *LoginFrame) String() string { return proto.CompactTextString(m) }
func (*LoginFrame) ProtoMessage()    {}
func (*LoginFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *LoginFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginFrame.Unmarshal(m, b)
}
func (m *LoginFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginFrame.Marshal(b, m, deterministic)
}
func (m *LoginFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginFrame.Merge(m, src)
}
func (m *LoginFrame) XXX_Size() int {
	return xxx_messageInfo_LoginFrame.Size(m)
}
func (m *LoginFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginFrame.DiscardUnknown(m)
}

var xxx_messageInfo_LoginFrame proto.InternalMessageInfo

func (m *LoginFrame) GetProxyproto() PROXY_PROTO {
	if m != nil {
		return m.Proxyproto
	}
	return PROXY_PROTO_TCP
}

func (m *LoginFrame) GetClienttype() CLIENT_TYPE {
	if m != nil {
		return m.Clienttype
	}
	return CLIENT_TYPE_PROXY
}

func (m *LoginFrame) GetFromaddr() string {
	if m != nil {
		return m.Fromaddr
	}
	return ""
}

func (m *LoginFrame) GetToaddr() string {
	if m != nil {
		return m.Toaddr
	}
	return ""
}

func (m *LoginFrame) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginFrame) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LoginRspFrame struct {
	Ret                  bool     `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRspFrame) Reset()         { *m = LoginRspFrame{} }
func (m *LoginRspFrame) String() string { return proto.CompactTextString(m) }
func (*LoginRspFrame) ProtoMessage()    {}
func (*LoginRspFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *LoginRspFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRspFrame.Unmarshal(m, b)
}
func (m *LoginRspFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRspFrame.Marshal(b, m, deterministic)
}
func (m *LoginRspFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRspFrame.Merge(m, src)
}
func (m *LoginRspFrame) XXX_Size() int {
	return xxx_messageInfo_LoginRspFrame.Size(m)
}
func (m *LoginRspFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRspFrame.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRspFrame proto.InternalMessageInfo

func (m *LoginRspFrame) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *LoginRspFrame) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PingFrame struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingFrame) Reset()         { *m = PingFrame{} }
func (m *PingFrame) String() string { return proto.CompactTextString(m) }
func (*PingFrame) ProtoMessage()    {}
func (*PingFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *PingFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingFrame.Unmarshal(m, b)
}
func (m *PingFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingFrame.Marshal(b, m, deterministic)
}
func (m *PingFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingFrame.Merge(m, src)
}
func (m *PingFrame) XXX_Size() int {
	return xxx_messageInfo_PingFrame.Size(m)
}
func (m *PingFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PingFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PingFrame proto.InternalMessageInfo

func (m *PingFrame) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PongFrame struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongFrame) Reset()         { *m = PongFrame{} }
func (m *PongFrame) String() string { return proto.CompactTextString(m) }
func (*PongFrame) ProtoMessage()    {}
func (*PongFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *PongFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongFrame.Unmarshal(m, b)
}
func (m *PongFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongFrame.Marshal(b, m, deterministic)
}
func (m *PongFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongFrame.Merge(m, src)
}
func (m *PongFrame) XXX_Size() int {
	return xxx_messageInfo_PongFrame.Size(m)
}
func (m *PongFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PongFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PongFrame proto.InternalMessageInfo

func (m *PongFrame) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type OpenConnFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Toaddr               string   `protobuf:"bytes,2,opt,name=toaddr,proto3" json:"toaddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenConnFrame) Reset()         { *m = OpenConnFrame{} }
func (m *OpenConnFrame) String() string { return proto.CompactTextString(m) }
func (*OpenConnFrame) ProtoMessage()    {}
func (*OpenConnFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *OpenConnFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenConnFrame.Unmarshal(m, b)
}
func (m *OpenConnFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenConnFrame.Marshal(b, m, deterministic)
}
func (m *OpenConnFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenConnFrame.Merge(m, src)
}
func (m *OpenConnFrame) XXX_Size() int {
	return xxx_messageInfo_OpenConnFrame.Size(m)
}
func (m *OpenConnFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenConnFrame.DiscardUnknown(m)
}

var xxx_messageInfo_OpenConnFrame proto.InternalMessageInfo

func (m *OpenConnFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenConnFrame) GetToaddr() string {
	if m != nil {
		return m.Toaddr
	}
	return ""
}

type OpenConnRspFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ret                  bool     `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenConnRspFrame) Reset()         { *m = OpenConnRspFrame{} }
func (m *OpenConnRspFrame) String() string { return proto.CompactTextString(m) }
func (*OpenConnRspFrame) ProtoMessage()    {}
func (*OpenConnRspFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *OpenConnRspFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenConnRspFrame.Unmarshal(m, b)
}
func (m *OpenConnRspFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenConnRspFrame.Marshal(b, m, deterministic)
}
func (m *OpenConnRspFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenConnRspFrame.Merge(m, src)
}
func (m *OpenConnRspFrame) XXX_Size() int {
	return xxx_messageInfo_OpenConnRspFrame.Size(m)
}
func (m *OpenConnRspFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenConnRspFrame.DiscardUnknown(m)
}

var xxx_messageInfo_OpenConnRspFrame proto.InternalMessageInfo

func (m *OpenConnRspFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenConnRspFrame) GetRet() bool {
	if m != nil {
		return m.Ret
	}
	return false
}

func (m *OpenConnRspFrame) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CloseFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseFrame) Reset()         { *m = CloseFrame{} }
func (m *CloseFrame) String() string { return proto.CompactTextString(m) }
func (*CloseFrame) ProtoMessage()    {}
func (*CloseFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *CloseFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseFrame.Unmarshal(m, b)
}
func (m *CloseFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseFrame.Marshal(b, m, deterministic)
}
func (m *CloseFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseFrame.Merge(m, src)
}
func (m *CloseFrame) XXX_Size() int {
	return xxx_messageInfo_CloseFrame.Size(m)
}
func (m *CloseFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseFrame.DiscardUnknown(m)
}

var xxx_messageInfo_CloseFrame proto.InternalMessageInfo

func (m *CloseFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DataFrame struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Compress             bool     `protobuf:"varint,2,opt,name=compress,proto3" json:"compress,omitempty"`
	Crc                  string   `protobuf:"bytes,3,opt,name=crc,proto3" json:"crc,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Index                int32    `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataFrame) Reset()         { *m = DataFrame{} }
func (m *DataFrame) String() string { return proto.CompactTextString(m) }
func (*DataFrame) ProtoMessage()    {}
func (*DataFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *DataFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFrame.Unmarshal(m, b)
}
func (m *DataFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFrame.Marshal(b, m, deterministic)
}
func (m *DataFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFrame.Merge(m, src)
}
func (m *DataFrame) XXX_Size() int {
	return xxx_messageInfo_DataFrame.Size(m)
}
func (m *DataFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFrame.DiscardUnknown(m)
}

var xxx_messageInfo_DataFrame proto.InternalMessageInfo

func (m *DataFrame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataFrame) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *DataFrame) GetCrc() string {
	if m != nil {
		return m.Crc
	}
	return ""
}

func (m *DataFrame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DataFrame) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ProxyFrame struct {
	Type                 FRAME_TYPE        `protobuf:"varint,1,opt,name=type,proto3,enum=FRAME_TYPE" json:"type,omitempty"`
	LoginFrame           *LoginFrame       `protobuf:"bytes,2,opt,name=loginFrame,proto3" json:"loginFrame,omitempty"`
	LoginRspFrame        *LoginRspFrame    `protobuf:"bytes,3,opt,name=loginRspFrame,proto3" json:"loginRspFrame,omitempty"`
	DataFrame            *DataFrame        `protobuf:"bytes,4,opt,name=dataFrame,proto3" json:"dataFrame,omitempty"`
	PingFrame            *PingFrame        `protobuf:"bytes,5,opt,name=pingFrame,proto3" json:"pingFrame,omitempty"`
	PongFrame            *PongFrame        `protobuf:"bytes,6,opt,name=pongFrame,proto3" json:"pongFrame,omitempty"`
	OpenFrame            *OpenConnFrame    `protobuf:"bytes,7,opt,name=openFrame,proto3" json:"openFrame,omitempty"`
	OpenRspFrame         *OpenConnRspFrame `protobuf:"bytes,8,opt,name=openRspFrame,proto3" json:"openRspFrame,omitempty"`
	CloseFrame           *CloseFrame       `protobuf:"bytes,9,opt,name=closeFrame,proto3" json:"closeFrame,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProxyFrame) Reset()         { *m = ProxyFrame{} }
func (m *ProxyFrame) String() string { return proto.CompactTextString(m) }
func (*ProxyFrame) ProtoMessage()    {}
func (*ProxyFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{8}
}

func (m *ProxyFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyFrame.Unmarshal(m, b)
}
func (m *ProxyFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyFrame.Marshal(b, m, deterministic)
}
func (m *ProxyFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyFrame.Merge(m, src)
}
func (m *ProxyFrame) XXX_Size() int {
	return xxx_messageInfo_ProxyFrame.Size(m)
}
func (m *ProxyFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyFrame.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyFrame proto.InternalMessageInfo

func (m *ProxyFrame) GetType() FRAME_TYPE {
	if m != nil {
		return m.Type
	}
	return FRAME_TYPE_LOGIN
}

func (m *ProxyFrame) GetLoginFrame() *LoginFrame {
	if m != nil {
		return m.LoginFrame
	}
	return nil
}

func (m *ProxyFrame) GetLoginRspFrame() *LoginRspFrame {
	if m != nil {
		return m.LoginRspFrame
	}
	return nil
}

func (m *ProxyFrame) GetDataFrame() *DataFrame {
	if m != nil {
		return m.DataFrame
	}
	return nil
}

func (m *ProxyFrame) GetPingFrame() *PingFrame {
	if m != nil {
		return m.PingFrame
	}
	return nil
}

func (m *ProxyFrame) GetPongFrame() *PongFrame {
	if m != nil {
		return m.PongFrame
	}
	return nil
}

func (m *ProxyFrame) GetOpenFrame() *OpenConnFrame {
	if m != nil {
		return m.OpenFrame
	}
	return nil
}

func (m *ProxyFrame) GetOpenRspFrame() *OpenConnRspFrame {
	if m != nil {
		return m.OpenRspFrame
	}
	return nil
}

func (m *ProxyFrame) GetCloseFrame() *CloseFrame {
	if m != nil {
		return m.CloseFrame
	}
	return nil
}

func init() {
	proto.RegisterEnum("PROXY_PROTO", PROXY_PROTO_name, PROXY_PROTO_value)
	proto.RegisterEnum("CLIENT_TYPE", CLIENT_TYPE_name, CLIENT_TYPE_value)
	proto.RegisterEnum("FRAME_TYPE", FRAME_TYPE_name, FRAME_TYPE_value)
	proto.RegisterType((*LoginFrame)(nil), "LoginFrame")
	proto.RegisterType((*LoginRspFrame)(nil), "LoginRspFrame")
	proto.RegisterType((*PingFrame)(nil), "PingFrame")
	proto.RegisterType((*PongFrame)(nil), "PongFrame")
	proto.RegisterType((*OpenConnFrame)(nil), "OpenConnFrame")
	proto.RegisterType((*OpenConnRspFrame)(nil), "OpenConnRspFrame")
	proto.RegisterType((*CloseFrame)(nil), "CloseFrame")
	proto.RegisterType((*DataFrame)(nil), "DataFrame")
	proto.RegisterType((*ProxyFrame)(nil), "ProxyFrame")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x4f, 0xdb, 0x40,
	0x10, 0x25, 0x76, 0xbe, 0x3c, 0x4e, 0xa2, 0x65, 0x55, 0x55, 0x11, 0xaa, 0x04, 0xca, 0x09, 0x51,
	0xe4, 0x43, 0x00, 0xf5, 0x4c, 0x8d, 0x41, 0x11, 0x21, 0xb6, 0x26, 0x69, 0x55, 0x7a, 0x41, 0xae,
	0xbd, 0x45, 0x56, 0x13, 0xaf, 0xe5, 0xf8, 0x40, 0xfe, 0x4d, 0x7f, 0x4b, 0x7f, 0x59, 0xb5, 0xe3,
	0xcf, 0x50, 0xd4, 0xdb, 0xdb, 0x7d, 0x6f, 0x76, 0xe7, 0xcd, 0x3e, 0x1b, 0xcc, 0x24, 0x95, 0x2f,
	0x3b, 0x2b, 0x49, 0x65, 0x26, 0x27, 0x7f, 0x5a, 0x00, 0x73, 0xf9, 0x1c, 0xc5, 0xb7, 0xa9, 0xbf,
	0x11, 0xfc, 0x1c, 0x80, 0x58, 0x22, 0xc7, 0xad, 0x93, 0xd6, 0xe9, 0x68, 0x3a, 0xb0, 0x3c, 0x74,
	0xbf, 0x3d, 0x3e, 0x79, 0xe8, 0xae, 0x5c, 0x6c, 0xf0, 0x4a, 0x1d, 0xac, 0x23, 0x11, 0x67, 0xd9,
	0x2e, 0x11, 0x63, 0xad, 0x50, 0xdb, 0xf3, 0x99, 0xb3, 0x58, 0x3d, 0xad, 0x1e, 0x3d, 0x07, 0x1b,
	0x3c, 0x3f, 0x82, 0xfe, 0xcf, 0x54, 0x6e, 0xfc, 0x30, 0x4c, 0xc7, 0xfa, 0x49, 0xeb, 0xd4, 0xc0,
	0x6a, 0xcd, 0xdf, 0x43, 0x37, 0x93, 0xc4, 0xb4, 0x89, 0x29, 0x56, 0x9c, 0x43, 0x3b, 0xf6, 0x37,
	0x62, 0xdc, 0xa1, 0x5d, 0xc2, 0x9c, 0x81, 0xfe, 0x4b, 0xec, 0xc6, 0x5d, 0xda, 0x52, 0x70, 0x72,
	0x01, 0x43, 0xf2, 0x80, 0xdb, 0x24, 0xb7, 0xc1, 0x40, 0x4f, 0x45, 0x46, 0xfd, 0xf7, 0x51, 0x41,
	0xb5, 0xb3, 0xd9, 0x3e, 0x53, 0x8f, 0x06, 0x2a, 0x38, 0x39, 0x06, 0xc3, 0x8b, 0xe2, 0xe7, 0xbc,
	0x80, 0x43, 0x3b, 0x8b, 0x36, 0x82, 0x2a, 0x74, 0x24, 0x4c, 0x02, 0xf9, 0x3f, 0xc1, 0x27, 0x18,
	0xba, 0x89, 0x88, 0x6d, 0x19, 0x17, 0xd3, 0x1b, 0x81, 0x16, 0x85, 0x24, 0x31, 0x50, 0x8b, 0xc2,
	0x86, 0x2b, 0xad, 0xe9, 0x6a, 0x72, 0x0b, 0xac, 0x2c, 0xac, 0x5a, 0x7e, 0x5d, 0x5b, 0x58, 0xd0,
	0xfe, 0xb1, 0xa0, 0xd7, 0x16, 0x3e, 0x00, 0xd8, 0x6b, 0xb9, 0x15, 0x6f, 0x9e, 0x30, 0xd9, 0x82,
	0x71, 0xe3, 0x67, 0xfe, 0xdb, 0xc7, 0x1f, 0x41, 0x3f, 0x90, 0x9b, 0x24, 0x15, 0xdb, 0x6d, 0x71,
	0x47, 0xb5, 0x56, 0x17, 0x05, 0x69, 0x50, 0x5e, 0x14, 0xa4, 0x81, 0x72, 0x1f, 0xfa, 0x99, 0x4f,
	0x8f, 0x33, 0x40, 0xc2, 0xfc, 0x1d, 0x74, 0xa2, 0x38, 0x14, 0x2f, 0xf4, 0x36, 0x1d, 0xcc, 0x17,
	0x93, 0xdf, 0x3a, 0x80, 0xa7, 0x12, 0x92, 0x5f, 0x7b, 0x0c, 0x6d, 0xca, 0x46, 0x9e, 0x24, 0xd3,
	0xba, 0xc5, 0xeb, 0x07, 0x27, 0x8f, 0x06, 0x11, 0xfc, 0x23, 0xc0, 0xba, 0x8a, 0x1f, 0x75, 0x62,
	0x4e, 0x4d, 0xab, 0x4e, 0x24, 0x36, 0x68, 0x7e, 0x09, 0xc3, 0x75, 0xf3, 0x9d, 0xa9, 0x45, 0x73,
	0x3a, 0xb2, 0xf6, 0x5e, 0x1f, 0xf7, 0x45, 0xfc, 0x14, 0x8c, 0xb0, 0x9c, 0x03, 0x39, 0x30, 0xa7,
	0x60, 0x55, 0x93, 0xc1, 0x9a, 0x54, 0xca, 0xa4, 0x8c, 0x04, 0xd9, 0x52, 0xca, 0x2a, 0x24, 0x58,
	0x93, 0xa4, 0x2c, 0xb3, 0x41, 0x49, 0x24, 0xa5, 0xac, 0x95, 0x55, 0x70, 0xce, 0xc1, 0x90, 0x89,
	0x28, 0xfc, 0xf5, 0x8a, 0x7e, 0xf7, 0x62, 0x83, 0xb5, 0x80, 0x5f, 0xc1, 0x40, 0x2d, 0x2a, 0x83,
	0x7d, 0x2a, 0x38, 0xb4, 0x5e, 0xc7, 0x05, 0xf7, 0x64, 0x6a, 0x8a, 0x41, 0x15, 0x84, 0xb1, 0x51,
	0x4c, 0xb1, 0xce, 0x06, 0x36, 0xe8, 0xb3, 0x4b, 0x30, 0x1b, 0x1f, 0x34, 0xef, 0x81, 0xbe, 0xb2,
	0x3d, 0x76, 0xa0, 0xc0, 0x97, 0x1b, 0x8f, 0xb5, 0x78, 0x1f, 0xda, 0xa8, 0x90, 0xc6, 0x0d, 0xe8,
	0xe0, 0xcc, 0x7e, 0xf0, 0x98, 0x7e, 0x76, 0x0f, 0x66, 0xe3, 0xc3, 0x56, 0x0c, 0x1d, 0xc2, 0x0e,
	0xf8, 0x21, 0x0c, 0xd1, 0xf9, 0xea, 0xe0, 0xd2, 0x79, 0xca, 0xb7, 0x5a, 0x1c, 0xa0, 0xbb, 0x74,
	0xed, 0xfb, 0xe5, 0x15, 0xd3, 0x38, 0x87, 0x51, 0x49, 0x17, 0x7b, 0xfa, 0x99, 0x00, 0xa8, 0x93,
	0xa0, 0xce, 0x9a, 0xbb, 0x77, 0xb3, 0x05, 0x3b, 0xe0, 0x03, 0xe8, 0x13, 0xc4, 0x65, 0xd1, 0xc8,
	0xcd, 0xf5, 0xea, 0x9a, 0x69, 0x0a, 0x79, 0xb3, 0xc5, 0x1d, 0xd3, 0x09, 0xb9, 0x8b, 0x3b, 0xd6,
	0x56, 0xc8, 0xf5, 0x9c, 0x05, 0xeb, 0x70, 0x13, 0x7a, 0x0a, 0xa9, 0xa2, 0xae, 0x3a, 0xcd, 0x9e,
	0xbb, 0x4b, 0x87, 0xf5, 0x3e, 0xf7, 0xbe, 0x77, 0xe8, 0x6f, 0xf5, 0xa3, 0x4b, 0xff, 0xab, 0x8b,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xc9, 0xd8, 0xda, 0xfb, 0x04, 0x00, 0x00,
}
